### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by lucapaganotti** [Chudleyj/IEX_CPP_API#1]
Hi, I made a fork of yor project and setup an eclipse project for building a library based on your code. The project is an autotools one, so eclipse isn't really needed to build up the library. If you're interested  have a look at https://github.com/lucapaganotti/IEX_CPP_API. Hope you'll enjoy, thanks for the good work! :-)

**Comment by Chudleyj** [comment]
Does this let someone simply run ./configure && make && make install and use this lib without any other installs? Thanks for your interest!!

**Comment by lucapaganotti** [comment]
Hi, provided that all the declared dependencies are satisfied (i.e. libcurl libcurlpp libjsoncpp) I think so. Actually only libcurl and libjsoncpp are needed, but I added also libcurlpp among dependencies for further development.
Have a good day !

**Comment by Chudleyj** [comment]
How do we set this up to include jsoncpp so someone can just download this repo, run ./confiure &&make && install and just be able to #include my lib and run with no issues? I'd love to get that setup and pull your code into my repo (with credit to you ofc)

**Comment by lucapaganotti** [comment]
Hi, you can clone my repository at https://github.com/lucapaganotti/IEX_CPP_API

You wil find in the project root folder the _libiex/libiex_ folder and the _Makefile.am_ file in it contains the list of dependencies:
...
_libiex_la_LDFLAGS = -lm -lz -lcurl -lcurlpp -ljsoncpp_
...

As I said curl and jsoncpp are mandatory dependencies as your code makes use of them, curlpp it's not really needed but I added it for future code enhancements, but you can omit its reference in the dependencies list changing the mentioned line in libiex/libiex/Makefile.am to

_libiex_la_LDFLAGS = -lm -lz -lcurl -ljsoncpp_

The library builds again with no errors.

You will find the relevant libraries (static and dynamic) in libiex/libiex/.libs folder inside the top source dir after running make.

For the time being I've not run make install as a final step to install the library in my system but I think that it should run out of the box.

I've not really written a single line of code except some very trivial changes to the example program, I've cloned your project and only re-organize it, so I need no credit :-) 
I could make you a pull request, but I think that's better for you to clone the repository and then change it to suite your needs, taking it separate from your original code so you can decide what to do. Another possibility could be to make a new branch of your project and pull my code in it, but that's your choice.

The next thing I plan to do is the writing of a doxygen file so to be able to easily document your code.

Have a good day :-)
