### ISSUE TITLE
Question concerning progression

### ISSUE THREAD

**Issue by JRizzle88** [Chudleyj/IEX_CPP_API#5]
By current code, you've done an impressive amount of integrations and methods involving the IEX API. Based on the README, the market data namespace roadmap looks great as well. My main questions are ... Where do you plan on going with this? Have you stopped maintaining? Did you run into a roadblock? 

Please do let me know and maybe I can help.

PS. I know this is not a direct issue as GitHub places it but I figured it would be a great way to reach out :) 👍

**Comment by Chudleyj** [comment]
Hello, 

Apologies for the absolutely horrendous delay in reply. I’ve been busy starting a new professional career and had to put aside all my side projects for a while. 

I do plan on making a cloud version of this, starting very shortly. As for the road map, it will need revisited as I need to dive in and see what this new API is all about, so no promises there.
